pipeline {

    agent any

    tools {
        maven 'Maven'
        jdk 'Java21'
    }

    stages {

        stage('Git Checkout') {
            steps {
                // Explicitly tell Jenkins to look for the 'main' branch
                git branch: 'main', url: 'https://github.com/priyankashinde-patil/devops-cicdproject.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t demoapp .'
            }
        }

        stage('Docker Push') {
            steps {
                sh 'docker tag demoapp priyushinde/demoapp'
                sh 'docker push priyushinde/demoapp'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f deployment.yml'
                sh 'kubectl apply -f service.yml'
            }
        }
    }
}